name: GitHub Actions Build and Deploy Demo
on: [push]
jobs:
  build-and-deploy:
  runs-on: ubuntu-latest
  steps:

    - name: Checkout
    uses: actions/checkout@master

    - name: Deploy to GitHub Pages
    uses: JamesIves/github-pages-deploy-action@3.5.8
    env:
    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    BRANCH: gh-pages
    FOLDER: dist
    BUILD_SCRIPT: npm install && npm run build && npm run demo:build