name: NPM Version
on:
  workflow_dispatch:
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: package-info
        uses: nyaa8/package-info@v1.0.0
        with:
          path: '../../package.json'
          follow-symlinks: 'false'
