name: NPM Version
on:
  workflow_dispatch:
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: package-info
        uses: nyaa8/package-info@v1.0.0
        with:
          path: 'github-actions-demo/package.json'
          follow-symlinks: 'false'
